### ISSUE TITLE
Get all mailboxes only when changes on polling

### ISSUE THREAD

**Issue by alagane** [OpenPaaS-Suite/esn-frontend-inbox#402]
### Story
[390 As a user I want to reduce the amount of data when getting mailboxes](#390)

### Tasks
[391 Migrate to use Mailbox/changes of jmap-client-ts without altering the current behavior](#391)

From https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/391#issuecomment-805618868

### Todo

* [x] Maintain the state along side the mailbox cache array
* [x] Upon resync perform a Mailbox/changes call
* [x] If the state is the same then do nothing: we are up to date
* [x] If the state mismatches then getAllMailboxes (no pity!!!) and reset the mailbox cache
* [x] Decrease default mailbox polling time to 1 minute

This is simpler to implement because it is closer to today mailbox resync (Just always getAllMailboxes), but is beneficial (we getAllMailboxes only if something moves, not all the time).
